function [ bathLawMagnPairs, ...
           bathLawType ] = evaluate_bathLawInCatalog( idxTimeSpace, ...
                                                      mag, ...
                                                      iEvent, ...
                                                      triggerID, ...
                                                      eventID, ...
                                                      clusterID )
                                                  
    % Find index of largest magnitude event
    [maxAftershock, idxMax] = max( mag(idxTimeSpace) );
    bathLawMagnPairs        = [mag(iEvent), mag(iEvent)-maxAftershock];
    % Evaluate relation of the two events
    refEv                   = idxTimeSpace(idxMax);
    relationScore           = sum([triggerID(refEv)==eventID(iEvent), clusterID(refEv)==clusterID(iEvent)]);
    bathLawType             = [mag(iEvent), relationScore];                                         
                                                  
end