function [ Settings4SynthSeq, ...
           magnDistr, ...
           tProductivity, ...
           tAnalysis, ...
           tAnalysis_detail ] = prepare_synthSequenceSimulation( Settings4SynthSeq, ...
                                                                    ModelAnalysis, ...
                                                                    Catalog, ...
                                                                    TargetWindow, ...
                                                                    SpatKernel, ...
                                                                    Tectonics, ...
                                                                    OmoriLaw, ...
                                                                    paramETAS, ...
                                                                    beta )
    
    %% Magnitude sampling method 
    if strcmp(Settings4SynthSeq.magnSampling, 'beta')
        magnDistr = beta;
    elseif strcmp(Settings4SynthSeq.magnSampling, 'original magnitudes')
        magnDistr = Catalog.mag;
    else
        error('Invalid choice of magnitude sampling method')
    end
    
    %% Length of simulation period
    Settings4SynthSeq.nDays = days(Settings4SynthSeq.timeWindow(2)-Settings4SynthSeq.timeWindow(1));
    
    %% Aftershock productivity
    tProductivity           = compute_productivityScaling( Settings4SynthSeq.tempExtent, ...
                                                            paramETAS, ...
                                                            TargetWindow, ...
                                                            SpatKernel, ...
                                                            Tectonics, ...
                                                            OmoriLaw, ...
                                                            ModelAnalysis.g_inn, ...
                                                            ModelAnalysis.f_inn );  
    
    %% Output struct and table
    % tAnalysis_detail
    tAnalysis_detail = struct('setOfSequences', [], 'clusterSize_1', [], 'clusterSize_2', [], ...
                             'meanTimeDiff', [], 'maxTimeDiff', [], ...
                             'meanDistance', [], 'maxDistance', [], ...
                             'bathLawMagn_1', [], 'bathLawMagn_2', [], ...
                             'dDoublet04_1', [], 'dDoublet04_2', []);
    % tAnalysis
    nTriggerMagn                = length(Settings4SynthSeq.triggerMagn);
    tAnalysis                   = table;
    tAnalysis.triggerMagn       = cell(nTriggerMagn,1);
    tAnalysis.mainMw            = zeros(nTriggerMagn,1);
    tAnalysis.clusterSize_1     = zeros(nTriggerMagn,3);
    tAnalysis.clusterSize_2     = zeros(nTriggerMagn,3);
    tAnalysis.meanTimeDiff      = zeros(nTriggerMagn,3);
    tAnalysis.maxTimeDiff       = zeros(nTriggerMagn,3);
    tAnalysis.meanDistance      = zeros(nTriggerMagn,3);
    tAnalysis.maxDistance       = zeros(nTriggerMagn,3);
    tAnalysis.bathLawMagn_1     = zeros(nTriggerMagn,3);
    tAnalysis.bathLawMagn_2     = zeros(nTriggerMagn,3);
    tAnalysis.percDoublets04_1  = zeros(nTriggerMagn,3);
    tAnalysis.percDoublets04_2  = zeros(nTriggerMagn,3);
    
end