function backgrIntegral = compute_backgrIntegral( bandwidth, ....
                                                    r_squ, ...
                                                    r0_squ, ...
                                                    segmFactor, ...
                                                    isStartP, ...
                                                    isEndP ) 

    % Precompute cumulative density function (cdf) values for event-to-polygon distances
    tmp_r  = 1 - exp( -r_squ ./ ( 2*bandwidth.^2 ) );
    tmp_r0 = 1 - exp( -r0_squ ./ ( 2*bandwidth.^2 ) );
    backgrIntegral = compute_integrPerEvent( segmFactor, ...
                                                                    isStartP, ...
                                                                    isEndP, ...
                                                                    tmp_r, ...
                                                                    tmp_r0 );

%                 close all
%                 plot_isoSpatPrecomp( IsoGrid, ...
%                                     Catalog, ...
%                                     iEvent )
%                 xlabel(['Background integral = ', num2str(backgrIntegral(jTargetEvent))])

    % Check if background integral values are between 0 and 1
    eps = 10^(-5);
    if backgrIntegral < - eps || backgrIntegral > 1 + eps
        error(['Background integral of event ', num2str(iEvent), ' is not in [0, 1]'])
    end
                
end