function tAnalysis = simulate_synthCatalogs( SimulInputs )
  
    tStart = tic;
    
    %% Preprocess inputs
    [ BackgrDistr, ...
      InitialEventSet, ...
      paramETAS ] = preprocess_catalogSimulationInputs( SimulInputs );
  
    %% Initialize tAnalysis
    tAnalysis = create_analysisTable4catalogs( ExperimentSettings.nRealizations );

   
%     %% Analyze Observations
%     tAnalysis_observed = analyze_catalogs( Observations, ...
%                                            AnalysisSettings, ...
%                                            GeneralSettings.spaceUnit, ...
%                                            SimulSettings, ...
%                                            -1, ...
%                                            true );
                                 
    % Loop over realizations
    for iRealiz = 1:ExperimentSettings.nRealizations
%         tic
        %% Produce synthetic catalogs
        SynthCatalog = simulate_synthEventSets( InitialEventSet, ...
                                                BackgrDistr, ...
                                                paramETAS, ...
                                                ExperimentSettings, ...
                                                SpaceSettings, ...
                                                TargetSettings, ...
                                                ModelFuncs, ...
                                                ModelSettings.modelType );
                                                    
%         %% Analyze catalogs           
%         tAnalysis(iRealiz+1,:) = analyze_catalogs( SynthCatalog, ...
%                                                      AnalysisSettings, ...
%                                                      GeneralSettings.spaceUnit, ...
%                                                      SimulSettings, ...
%                                                      iRealiz, ...
%                                                      true );
                                             
        if mod(iRealiz, 500)==0
            disp(['Simulated ', num2str(iRealiz), ' out of ', num2str(SimulSettings.nRealizations), ' realization.'])
        end
%         toc
    end
    
    tEnd = toc(tStart)/60;
    disp(['Elapsed time for catalog simulation is ', num2str(tEnd), ' minutes.'])
    
end