function [ fval_logL, ...
            grad_logL, ...
            integratedRate, ...
            anisoPeaks] = estimate_loglikSwitch( inclGrad, ...
                                                 Catalog, ...
                                                 Inputs, ...
                                                 ModelFuncs, ...
                                                 sqrtParamETAS, ...
                                                 aggregBackgrRate, ...
                                                 SpatData, ...
                                                 TempData, ...
                                                 writeLog )
        
    %% Standard ETAS Model
    if strcmp( Inputs.ModelSettings.modelType, 'ETAS' ) 
        [ fval_logL, ...
            grad_logL, ...
            integratedRate, ...
            anisoPeaks] = estimate_loglikEtas( inclGrad, ...
                                                 Catalog, ...
                                                 Inputs, ...
                                                 ModelFuncs, ...
                                                 sqrtParamETAS, ...
                                                 aggregBackgrRate, ...
                                                 SpatData );
        
    else 
        [ fval_logL, ...
            grad_logL, ...
            integratedRate, ...
            anisoPeaks] = estimate_loglikEtasIncomplete( inclGrad, ...
                                                         Catalog, ...
                                                         Inputs, ...
                                                         ModelFuncs, ...
                                                         sqrtParamETAS, ...
                                                         aggregBackgrRate, ...
                                                         SpatData, ...
                                                         TempData, ...
                                                         writeLog );
        
    end
                                             
end