function [ ModelDiagnostic, hessMatrix, nIter ] = initialize_etasVariables( nParam )

    nIter           = 11;
    hessMatrix      = diag(ones(nParam,1));
    ModelDiagnostic = struct('loglik_fval', zeros(2, 1),        ... 
                             'loglik_grad', zeros(2, nParam),   ... 
                             'aic',         zeros(2,1),         ...
                             'paramETAS',   zeros(2, nParam), ...
                             'integratedRate', zeros(2,1) ); %,   ...
%                              'avcov',       zeros(nParam, nParam),  ..., ...
%                              'iIter',       zeros(0, nParam)
%                              'asd',         zeros(nIter, nParam),   ...
%                              'lastIter',    0 );

end