function integrPerEvent = compute_integrPerEvent( iWeights, iIsLower, iIsUpper, tmp_r, tmp_r0 )

    integrPerEvent = sum( iWeights .*...
                                ( 1/6* tmp_r(iIsLower) + ...
                                  2/3* tmp_r0 + ...
                                  1/6* tmp_r(iIsUpper) ...
                                ) ...
                     	);

end