function [ SimulSettings, ...
              SimulAnalysis, ...
              Catalog, ...
              paramETAS, ...
              ModelAnalysis, ...
              GeneralSettings, ...
              OmoriLaw, ...
              SpatKernel, ...
              Tectonics, ...
              EventPropertyFuncs ] = load_simulationInputs( strNameSimulSettings )
          
    %% Load specific simulation settings  
    filename = ['Simulation_settings_', strNameSimulSettings, '.mat'];
    load(filename, 'SimulSettings', 'SimulAnalysis')
    
    %% Load ETAS estimation settings and results
    % Note: TargetWindow is replaced by specific simulation settings
    load('Estimation_results.mat', 'Inputs', 'Catalog', 'paramETAS', 'ModelAnalysis', 'EventPropertyFuncs')
    GeneralSettings = Inputs.GeneralSettings;
    OmoriLaw        = Inputs.OmoriLaw;
    SpatKernel      = Inputs.SpatKernel;
    Tectonics       = Inputs.Tectonics;
          
end