function [Inputs, ModelFuncs] = preprocess_estimationSettings( Inputs )

    ModelFuncs                  = struct;
    
    Inputs.ModelSettings        = preprocess_modelSettings( Inputs.ModelSettings );
    
    [ Inputs.TargetSettings, ...
      ModelFuncs ]              = preprocess_targetSettings( Inputs.TargetSettings, ...
                                                             ModelFuncs );
    [ Inputs.SpaceSettings, ...
      ModelFuncs ]              = preprocess_spaceSettings( Inputs.SpaceSettings, ...
                                                            Inputs.ModelSettings.spaceModel, ...
                                                            ModelFuncs );
                                                        
    [ Inputs.TimeSettings, ...
      ModelFuncs  ]             = preprocess_timeSettings( Inputs.TimeSettings, ...
                                                           Inputs.TargetSettings, ...
                                                           ModelFuncs);

end